"""Pick 4 hero citizens for the demo path and write data/scenarios/heroes.json (CLAUDE.md §10).

A hero must get worse under the demo scenario and better again under the engine's top fix,
so the "she's served now" moment really happens. Criteria are relaxed step by step if nobody
matches exactly. Re-run after the population or scenarios change.

    python -m scripts.pick_heroes [scenario_id]
"""
import json
import sys

from app.config import SCENARIOS_DIR
from app.sim import engine, fixgrid, world
from app.sim.engine import STATUS_RANK

WANTED = [
    ("Elderly woman in east Amman with no car; a family member helps her",
     [lambda c: "elderly" in c["tags"] and c["gender"] == "f" and not c["has_car"] and c["has_helper"] and c["area"] == "marka",
      lambda c: "elderly" in c["tags"] and c["gender"] == "f" and not c["has_car"] and c["has_helper"],
      lambda c: "elderly" in c["tags"] and not c["has_car"]]),
    ("Wheelchair user",
     [lambda c: c["mobility"] == "wheelchair" and c["area"] == "wehdat",
      lambda c: c["mobility"] == "wheelchair",
      lambda c: c["mobility"] != "none"]),
    ("Factory worker on an early shift",
     [lambda c: c["works"] and c["work_start"] == "07:00" and c["area"] == "tabarbour",
      lambda c: c["works"] and c["work_start"] == "07:00",
      lambda c: c["works"] and "offline" in c["tags"]]),
    ("Offline resident with nobody to help",
     [lambda c: "offline" in c["tags"] and not c["has_helper"] and world.areas()[c["area"]]["side"] == "east",
      lambda c: "offline" in c["tags"] and not c["has_helper"]]),
]


def profile(c: dict) -> str:
    """Factual one-liner, so the demo script never describes a hero wrongly."""
    where = c.get("neighbourhood") or c["area"]
    bits = [f"{c['age']}{c['gender']}", where, f"mobility {c['mobility']}", "car" if c["has_car"] else "no car",
            "smartphone" if c["has_smartphone"] else "no smartphone", f"digital literacy {c['digital_literacy']}",
            f"works {c['work_start']}-{c['work_end']}" if c["works"] else "not working",
            f"helper: {c['helper_relation_en']}" if c["has_helper"] else "no helper"]
    return ", ".join(bits)


def main(scenario_id: str | None = None) -> None:
    scenario_id = scenario_id or world.demo_scenario_id()
    pop = world.population()
    base = engine.run(world.scenario_policy("baseline"))
    scen = engine.run(world.scenario_policy(scenario_id))
    fix = engine.run(fixgrid.top_fixes(world.scenario_policy(scenario_id))[0].policy)
    rank = lambda o: STATUS_RANK[o["status"]]
    heroes, used = [], set()
    for note, tiers in WANTED:
        pick = None
        for strict in (True, False):  # first: worse in scenario AND better with the fix; then: just worse
            for test in tiers:
                for i, c in enumerate(pop):
                    if c["id"] in used or not test(c) or rank(scen[i]) <= rank(base[i]):
                        continue
                    if strict and rank(fix[i]) >= rank(scen[i]):
                        continue
                    pick = (i, c, strict)
                    break
                if pick:
                    break
            if pick:
                break
        if not pick:
            print("no match for:", note)
            continue
        i, c, strict = pick
        used.add(c["id"])
        heroes.append({"citizen_id": c["id"], "wanted": note, "profile": profile(c), "name_en": c["name_en"], "area": c["area"],
                       "baseline": base[i]["status"], "scenario": scen[i]["status"], "with_top_fix": fix[i]["status"],
                       "recovers_with_fix": strict})
        print(f"{c['id']} {c['name_en']:12s} {c['area']:16s} {base[i]['status']:>9} -> {scen[i]['status']:<9} -> fix: {fix[i]['status']:<9} | {profile(c)}")
    out = {"scenario": scenario_id, "_note": "Generated by scripts/pick_heroes.py. Synthetic citizens.", "heroes": heroes}
    (SCENARIOS_DIR / "heroes.json").write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")


if __name__ == "__main__":
    main(*sys.argv[1:])
