"""Shared building blocks for the synthetic population (used by seed_census.py).

The population itself is generated by `python -m app.data.seed_census --install`.
This module holds what that generator reuses: generic first names, work shifts, the
helper assumptions, and the official tag rules (CLAUDE.md §5). Names are generic first
names, not real people.
"""
from __future__ import annotations

import json
import random
from pathlib import Path

DATA = Path(__file__).resolve().parent
AREAS = json.loads((DATA / "areas.json").read_text(encoding="utf-8"))["areas"]

# Shift patterns (start, end, weight). ASSUMPTION. East areas get more early factory shifts.
SHIFTS = [("07:00", "16:00", 0.20), ("08:00", "15:00", 0.25), ("08:00", "16:00", 0.25),
          ("09:00", "17:00", 0.20), ("10:00", "18:00", 0.10)]

# Has a family member or neighbour who can drive them or help online. ASSUMPTION.
HELPER_BY_AGE = {"16-24": 0.70, "25-64": 0.55, "65+": 0.72}

NAMES_M = [("محمد", "Mohammad"), ("أحمد", "Ahmad"), ("عمر", "Omar"), ("خالد", "Khaled"), ("يوسف", "Yousef"),
           ("إبراهيم", "Ibrahim"), ("علي", "Ali"), ("حسن", "Hasan"), ("محمود", "Mahmoud"), ("عبدالله", "Abdullah"),
           ("سامي", "Sami"), ("فادي", "Fadi"), ("زيد", "Zaid"), ("ليث", "Laith"), ("طارق", "Tareq"),
           ("ماهر", "Maher"), ("نبيل", "Nabil"), ("رامي", "Rami"), ("هاني", "Hani"), ("بلال", "Bilal"),
           ("أنس", "Anas"), ("مصطفى", "Mustafa"), ("سليمان", "Suleiman"), ("عيسى", "Issa"), ("جمال", "Jamal")]
NAMES_F = [("فاطمة", "Fatima"), ("مريم", "Maryam"), ("سارة", "Sara"), ("نور", "Noor"), ("هدى", "Huda"),
           ("رنا", "Rana"), ("ليلى", "Layla"), ("سلمى", "Salma"), ("آمنة", "Amina"), ("خديجة", "Khadija"),
           ("رهف", "Rahaf"), ("دانا", "Dana"), ("لينا", "Lina"), ("سعاد", "Suad"), ("نادية", "Nadia"),
           ("أم محمد", "Um Mohammad"), ("وفاء", "Wafaa"), ("سميرة", "Samira"), ("رولا", "Rula"), ("عبير", "Abeer"),
           ("هالة", "Hala"), ("زينب", "Zainab"), ("جميلة", "Jamila"), ("تهاني", "Tahani"), ("ريم", "Reem")]


def weighted(rng: random.Random, items):
    total = sum(w for *_, w in items)
    r = rng.random() * total
    for item in items:
        r -= item[-1]
        if r <= 0:
            return item
    return items[-1]


def band(age: int, kind: str) -> str:
    if kind == "helper":
        return "16-24" if age < 25 else "25-64" if age < 65 else "65+"
    raise ValueError(kind)


def helper_relation(rng: random.Random, age: int, gender: str):
    if age >= 60:
        options = [("ابني", "my son", 0.45), ("بنتي", "my daughter", 0.35), ("حفيدي", "my grandson", 0.12), ("جاري", "my neighbour", 0.08)]
    elif age >= 25:
        spouse = ("زوجي", "my husband", 0.35) if gender == "f" else ("زوجتي", "my wife", 0.25)
        options = [spouse, ("أخوي", "my brother", 0.30), ("أختي", "my sister", 0.15), ("جاري", "my neighbour", 0.10)]
    else:
        options = [("أبوي", "my father", 0.45), ("أخوي", "my brother", 0.30), ("أمي", "my mother", 0.25)]
    ar, en, _ = weighted(rng, options)
    return ar, en


def derive_tags(c: dict) -> list[str]:
    tags = []
    if c["age"] >= 65: tags.append("elderly")
    if c["mobility"] != "none": tags.append("disabled")
    if c["income_band"] == "low": tags.append("low_income")
    if not c["has_car"]: tags.append("no_car")
    if not c["has_smartphone"] or c["digital_literacy"] == "low": tags.append("offline")
    if c["works"]: tags.append("worker")
    if 18 <= c["age"] <= 24 and not c["works"]: tags.append("student")
    return tags
